### ISSUE TITLE
Avro::Schema not found.

### ISSUE THREAD

**Issue by jackiig** [alivraghi/Confluent-Avro-Producer#4]
It appears that Avro::Schema is [no longer found on MetaCPAN](https://metacpan.org/search?size=20&q=Avro%3A%3ASchema).  

Are there any other install paths for that module?  Or possible replacements?

**Comment by alivraghi** [comment]
Avro::Schema is now fully available on MetaCpan under the [Avro distribution](https://metacpan.org/source/RSKRABA/Avro-1.10.1).
